name: AfkPoolRewards
version: '1.0-SNAPSHOT'
main: org.clokyy.afkpoolrewards.AfkPoolRewards
api-version: 1.19
author: Clokyy
depend:
  - WorldGuard
  - Essentials
commands:
  afktime:
    description: Check how long a user has been afk for.
    usage: /afktime <player>
